# Exclude test files containing intentionally fake secrets for testing
# These are NOT real credentials - they use obvious patterns like "a1b2c3d4..."
paths-ignore:
  - 'tests/**'
  - 'test_*.sh'
  - '*_test.sh'
