name: 'libreleak'
description: 'Fast, offline secret scanner'
author: 'fosscode'

inputs:
  path:
    description: 'Path to scan'
    default: '.'
  fail-on-leak:
    description: 'Fail the workflow if secrets are found'
    default: 'true'
  format:
    description: 'Output format (text, json, sarif, report)'
    default: 'text'
  exclude-rules:
    description: 'Comma-separated list of rule IDs to exclude'
    default: ''
  only-rules:
    description: 'Comma-separated list of rule IDs to include'
    default: ''

outputs:
  findings:
    description: 'Number of secrets found'
    value: ${{ steps.scan.outputs.findings }}

runs:
  using: 'composite'
  steps:
    - name: Setup Rust
      uses: dtolnay/rust-toolchain@stable

    - name: Cache cargo
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-libreleak-${{ hashFiles('**/Cargo.lock') }}

    - name: Build libreleak
      shell: bash
      run: |
        cd ${{ github.action_path }}
        cargo build --release

    - name: Run scan
      id: scan
      shell: bash
      run: |
        ARGS="${{ inputs.path }}"

        if [ "${{ inputs.fail-on-leak }}" = "true" ]; then
          ARGS="$ARGS --fail-on-leak"
        fi

        if [ -n "${{ inputs.format }}" ]; then
          ARGS="$ARGS --format ${{ inputs.format }}"
        fi

        if [ -n "${{ inputs.exclude-rules }}" ]; then
          ARGS="$ARGS --exclude ${{ inputs.exclude-rules }}"
        fi

        if [ -n "${{ inputs.only-rules }}" ]; then
          ARGS="$ARGS --only ${{ inputs.only-rules }}"
        fi

        # Run scan and capture output
        set +e
        OUTPUT=$(${{ github.action_path }}/target/release/libreleak $ARGS 2>&1)
        EXIT_CODE=$?
        set -e

        echo "$OUTPUT"

        # Extract findings count from output
        if echo "$OUTPUT" | grep -q "Found [0-9]* potential secret"; then
          FINDINGS=$(echo "$OUTPUT" | grep -o "Found [0-9]* potential secret" | grep -o "[0-9]*")
        elif echo "$OUTPUT" | grep -q "No secrets found"; then
          FINDINGS=0
        else
          # For JSON/SARIF, count rule_id occurrences
          FINDINGS=$(echo "$OUTPUT" | grep -c '"rule_id"' || echo "0")
        fi

        echo "findings=$FINDINGS" >> $GITHUB_OUTPUT

        exit $EXIT_CODE

branding:
  icon: 'shield'
  color: 'red'
